use strict;
use warnings;
@arr3 = (0...9);
@arr4 = @arr3[4...6];
print(@arr4);
print("\n");
@arr0 = (0...12);
@arr1 = (12...22);
@arr2 = (a...z);
print("@arr0\n");
print("@arr1\n");
print("@arr2\n");
print("------------\n");
@list = ('aaa','bbb','ccc');
print("\@list = @list\n");
print("------------\n");
$end = push(@list,'ddd');
print("\$end = $end\n");
print("\@list = @list\n");
print("------------\n");
$first = unshift(@list,'000');
print("$first = $first\n");
print("\@list = @list\n");
print("------------\n");
print(pop(@list));
print("\n");
print("\@list = @list\n");
print("------------\n");
print(shift(@list));
print("\n");
print("\@list = @list\n");
print("------------\n");
