$var0 = 1;
$var1 = "aa";
print("\$var0 = $var0 \n");
print("\$var1 = $var1 \n");
print("\$var2 = $var2 \n");
print("\n");
print("\n");
@list = ("a","b","c");
print("\@list = @list \n");
print("\$list[0] = $list[0] \n");
print("\$list[1] = $list[1] \n");
print("\$list[2] = $list[2] \n");
print("\$list[3] = $list[3] \n");
print("\n");
print("\n");
%data = ('0'=>'key0','1'=>'key1','2'=>'key2');
print("%data\n");
print("\$data{'0'} = $data{'0'}\n");
print("\$data{'1'} = $data{'1'}\n");
print("\$data{'2'} = $data{'2'}\n");
print("\n");
print("\n");