// import './example/symbol';
// import './example/basic-type';
// import './example/interface';
// import './example/function';
// import './example/generics';
// import './example/es6-class-0';
// import './example/class';
// import './example/enum';
// import './example/inference-compatibility';
// import './example/basicType';
import './example/officeTest';
console.log('hello index.ts');
